apiVersion: federation/v1beta1
kind: Cluster
metadata:
  name: london
spec:
  serverAddressByClientCIDRs:
    - clientCIDR: "0.0.0.0/0"
      serverAddress: "SERVER_ADDRESS"
  secretRef:
    name: london
